export const constant = {
  //loading status
  IDLE: "IDLE",
  SUCCESS: "SUCCESS",
  LOADING: "LOADING",
  FAIL: "FAIL",

  // base url
  API_URL: "http://localhost:3000",
  //pop up
  NO_POPUP: "NO_POPUP",
  CHANGE_POPUP: "CHANGE_POPUP",
  PRODUCT_INFO_POPUP: "PRODUCT_INFO_POPUP",
  //product
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",
  //language
  ENG: "ENG",
  VI: "VI",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  //category
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  //home
  GET_HOME_SUCCESS: "GET_HOME_SUCCESS",
};

export const LOADING_STATUS = {
  IDLE: "IDLE",
  LOADING: "LOADING",
  SUCCESS: "SUCCESS",
  FAIL: "FAIL",
};

export const PAGE_ACTIONS = {
  GET_BANNERS: "GET_BANNERS",
  GET_HOT_PRODUCTS: "GET_HOT_PRODUCTS",
};

export const POPUP = {
  NO_POPUP: "NO_POPUP",
  PRODUCT_INFO_POPUP: "PRODUCT_INFO_POPUP",
};
