export const constant = {
  SUCCESS: "SUCCESS",
  LOADING: "LOADING",
  API_URL: "http://localhost:3000",
  //pop up
  NO_POPUP: "NO_POPUP",
  CHANGE_POPUP: "CHANGE_POPUP",
  PRODUCT_INFO_POPUP: "PRODUCT_INFO_POPUP",
  //product
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",
  //language
  ENG: "ENG",
  VI: "VI",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  //category
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  //home
  GET_HOME_SUCCESS: "GET_HOME_SUCCESS",
};
